import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Add_Student.java
 *
 * Created on Nov 9, 2016, 2:51:40 PM
 */

/**
 *
 * @author admin
 */
public class Add_Student extends javax.swing.JFrame {

    /** Creates new form Add_Student */
    public Add_Student() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtRno = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtClass = new javax.swing.JTextField();
        txtSec = new javax.swing.JTextField();
        txtscience = new javax.swing.JTextField();
        txtsst = new javax.swing.JTextField();
        txtMM = new javax.swing.JTextField();
        txtTM = new javax.swing.JTextField();
        txtPer = new javax.swing.JTextField();
        txtGrade = new javax.swing.JTextField();
        btnCal = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        PS = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txteng = new javax.swing.JTextField();
        txthin = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("ROLL NO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(46, 122, 50, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(46, 157, 31, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("CLASS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(48, 192, 35, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("SECTION");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(46, 230, 47, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("SCIENCE MARKS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(345, 122, 88, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("SOCIAL SCIENCE MARKS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(345, 157, 132, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("TOTAL MARKS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(345, 308, 79, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("PERCENTAGE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(46, 268, 70, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("GRADE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(46, 308, 38, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("PREFFERED STREAM");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(214, 377, 110, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("MATHS MARKS");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(345, 192, 83, 14);
        getContentPane().add(txtRno);
        txtRno.setBounds(168, 119, 99, 20);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(168, 150, 99, 20);
        getContentPane().add(txtClass);
        txtClass.setBounds(168, 189, 99, 20);
        getContentPane().add(txtSec);
        txtSec.setBounds(168, 227, 99, 20);
        getContentPane().add(txtscience);
        txtscience.setBounds(519, 119, 95, 20);
        getContentPane().add(txtsst);
        txtsst.setBounds(518, 157, 96, 20);
        getContentPane().add(txtMM);
        txtMM.setBounds(518, 189, 96, 20);

        txtTM.setEditable(false);
        getContentPane().add(txtTM);
        txtTM.setBounds(518, 303, 96, 20);

        txtPer.setEditable(false);
        getContentPane().add(txtPer);
        txtPer.setBounds(168, 265, 99, 20);

        txtGrade.setEditable(false);
        txtGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradeActionPerformed(evt);
            }
        });
        getContentPane().add(txtGrade);
        txtGrade.setBounds(168, 303, 99, 20);

        btnCal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCal.setText("CALCULATE");
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });
        getContentPane().add(btnCal);
        btnCal.setBounds(29, 424, 95, 23);

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(238, 424, 61, 23);

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(426, 424, 67, 23);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(572, 424, 61, 23);

        PS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PCM", "PCB", "COMMERCE" }));
        getContentPane().add(PS);
        PS.setBounds(332, 374, 108, 20);

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel12.setText("STUDENT DETAILS");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(213, 20, 241, 34);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("ENGLISH MARKS ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(345, 230, 93, 14);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("HINDI MARKS");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(348, 268, 76, 14);
        getContentPane().add(txteng);
        txteng.setBounds(518, 227, 96, 20);

        txthin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthinActionPerformed(evt);
            }
        });
        getContentPane().add(txthin);
        txthin.setBounds(518, 265, 96, 20);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1.jpg"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 680, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtNameActionPerformed

    private void txtGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtGradeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String RNo = txtRno.getText();
        String Nam = txtName.getText();
        int Cl = Integer.parseInt(txtClass.getText());
        String Sec = txtSec.getText();
        int SM = Integer.parseInt(txtscience.getText());
        int SST = Integer.parseInt(txtsst.getText());
        int MM = Integer.parseInt(txtMM.getText());
        int EM = Integer.parseInt(txteng.getText());
        int HM = Integer.parseInt(txthin.getText());
        int Total = Integer.parseInt(txtTM.getText());
        int Per = Integer.parseInt(txtPer.getText());
        String Gr = txtGrade.getText();
        String PSt = (String)PS.getSelectedItem();
         try
         {
             Class.forName("com.mysql.jdbc.Driver");
             Connection con = (Connection)
                     DriverManager.getConnection("jdbc:mysql://localhost:3306/Stream","root","damon");
             Statement stmt = con.createStatement();
             String str = "Insert into Student Values('"+RNo+"','"+Nam+"',"+Cl+",'"+Sec+"',"+SM+","+SST+","+MM+","+EM+","+HM+","+Total+","+Per+",'"+Gr+"','"+PSt+"', NULL"+")";
             int r = stmt.executeUpdate(str);
             JOptionPane.showMessageDialog(this,"RECORD ADDED");


             
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(this,e.getMessage());
         }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        // TODO add your handling code here:
        int sm = Integer.parseInt(txtscience.getText());
        int cm = Integer.parseInt(txtsst.getText());
        int mm = Integer.parseInt(txtMM.getText());
        int em= Integer.parseInt(txteng.getText());
        int hin = Integer.parseInt(txthin.getText());
        int TotalMarks = sm +cm+mm+em+hin;
        txtTM.setText("" + TotalMarks);
        int Percentage = TotalMarks/5;
        txtPer.setText("" + Percentage);
        if (Percentage>=90)
            txtGrade.setText("A");
        else if(Percentage>=80)
           txtGrade.setText("B");
        else if (Percentage>=70)
            txtGrade.setText("C");
        else
            txtGrade.setText("D");


    }//GEN-LAST:event_btnCalActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtRno.setText("");
        txtName.setText("");
        txtClass.setText("");
        txtSec.setText("");
        txtscience.setText("");
        txtsst.setText("");
        txtMM.setText("");
        txtTM.setText("");
        txthin.setText("");
        txteng.setText("");
        
        txtPer.setText("");
        txtGrade.setText("");
       
         
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
                    new Menu().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txthinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthinActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox PS;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCal;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtMM;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPer;
    private javax.swing.JTextField txtRno;
    private javax.swing.JTextField txtSec;
    private javax.swing.JTextField txtTM;
    private javax.swing.JTextField txteng;
    private javax.swing.JTextField txthin;
    private javax.swing.JTextField txtscience;
    private javax.swing.JTextField txtsst;
    // End of variables declaration//GEN-END:variables

}
