import javax.swing.JOptionPane;
import java.sql.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogIN.java
 *
 * Created on Nov 6, 2016, 2:16:30 PM
 */

/**
 *
 * @author Administrator
 */
public class LogIN extends javax.swing.JFrame {

    /** Creates new form LogIN */
    public LogIN() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUID = new javax.swing.JTextField();
        txtPWD = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("LOGIN ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 110, 60, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("PASSWORD");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 150, 70, 14);
        getContentPane().add(txtUID);
        txtUID.setBounds(200, 100, 110, 20);
        getContentPane().add(txtPWD);
        txtPWD.setBounds(200, 140, 110, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 120, 69, 23);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setText("LOGIN FORM");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 20, 161, 34);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hello.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 650, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String LogIN = txtUID.getText();
        String Password = new String(txtPWD.getPassword());
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/stream","root","damon");
            Statement stmt = con.createStatement();
            String str = "Select* from LogIN";
            ResultSet rs = stmt.executeQuery(str);
            if(rs.next())
            {
                String mUID = rs.getString("UID");
                String mPWD = rs.getString("PWD");
                if(LogIN.equals(mUID)&&Password.equals(mPWD))
                {
                    this.setVisible(false);
                    new Menu().setVisible(true);
                    
                  
                }
                else JOptionPane.showMessageDialog(this,"Incorrect Password");
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtPWD;
    private javax.swing.JTextField txtUID;
    // End of variables declaration//GEN-END:variables

}
